service: serverless-express

plugins:
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /api/v1/{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
